// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcarsMessage struct {
	ID        int64
	Timestamp pgtype.Timestamptz
	StationID pgtype.Text
	Channel   int32
	Freq      float64
	Level     float64
	Error     int32
	Mode      string
	Label     string
	BlockID   pgtype.Text
	Tail      pgtype.Text
	Flight    pgtype.Text
	Msgno     pgtype.Text
	Text      pgtype.Text
	End       bool
	Depa      pgtype.Text
	Dsta      pgtype.Text
	Eta       pgtype.Text
	Gtout     pgtype.Text
	Gtin      pgtype.Text
	Wloff     pgtype.Text
	Won       pgtype.Text
	Sublabel  pgtype.Text
	Mfi       pgtype.Text
	Assstat   pgtype.Text
	Libacars  []byte
	AppName   string
	AppVer    string
}
